# Generated by Django 5.2 on 2025-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(help_text='distance in kilometers'),
        ),
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.PositiveIntegerField(help_text='amount of cargo units (unit stores passengers cargo)'),
        ),
        migrations.AlterField(
            model_name='train',
            name='places_in_cargo',
            field=models.PositiveIntegerField(help_text='describes how many places in one cargo unit'),
        ),
    ]
