# Generated by Django 5.2 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_alter_route_distance_alter_train_cargo_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cargo',
            field=models.PositiveIntegerField(default=0, help_text='one cargo unit is 10 kg (9kg - 1 unit, 10kg - 1 unit, 11kg - 2 units)'),
        ),
    ]
