# Generated by Django 5.2 on 2025-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_alter_ticket_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='train',
            name='cargo_num',
        ),
        migrations.RemoveField(
            model_name='train',
            name='places_in_cargo',
        ),
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(related_name='journeys', to='railway.crew'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_baggage_charge',
            field=models.BooleanField(default=False, help_text='Customer should pay extra fee if checked baggage exceeds min checked baggage mass.'),
        ),
        migrations.AddField(
            model_name='train',
            name='max_checked_baggage_mass',
            field=models.PositiveIntegerField(default=0, help_text='Passengers may bring one item of hand luggage. Checked baggage exceeding max checked baggage mass will incur an additional charge.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='min_checked_baggage_mass',
            field=models.PositiveIntegerField(default=0, help_text="If mass of checked baggage is less - customer shouldn't pay for it"),
            preserve_default=False,
        ),
    ]
