# Generated by Django 5.2 on 2025-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_remove_ticket_cargo_remove_train_cargo_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='max_checked_baggage_mass',
            field=models.PositiveIntegerField(blank=True, help_text='Passengers may bring one item of hand luggage. Checked baggage exceeding max checked baggage mass will incur an additional charge.', null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='min_checked_baggage_mass',
            field=models.PositiveIntegerField(blank=True, help_text="If mass of checked baggage is less - customer shouldn't pay for it", null=True),
        ),
    ]
