# Generated by Django 5.2 on 2025-05-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0005_alter_train_max_checked_baggage_mass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='name',
            new_name='number',
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'destination'), name='unique_route'),
        ),
    ]
