# Generated by Django 5.2 on 2025-05-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_rename_name_train_number_route_unique_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seats',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='railway.journey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('journey', 'number'), name='unique_seats')],
            },
        ),
    ]
