# Generated by Django 5.2 on 2025-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='max_checked_baggage_mass',
            field=models.PositiveIntegerField(default=12, help_text='Passengers may bring one item of hand luggage. Checked baggage exceeding max checked baggage mass will incur an additional charge.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='min_checked_baggage_mass',
            field=models.PositiveIntegerField(default=6, help_text="If mass of checked baggage is less - customer shouldn't pay for it"),
            preserve_default=False,
        ),
    ]
