# Generated by Django 5.2 on 2025-05-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_alter_train_max_checked_baggage_mass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['first_name', 'last_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-departure_time', 'id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-order__created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['train_type', 'number']},
        ),
        migrations.AlterModelOptions(
            name='traintype',
            options={'ordering': ['name', 'id']},
        ),
    ]
